# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 314503476d496a6cfda3010f4273181c2739ce21ac2c663c95fbcb8783d139b65a0a5cc14d1f4702c14442d0233991232e348f54421bb7e138bc638e2ff85d38

test:
  secret_key_base: 582cd97dcc2839f4b150772b3d4ac4422d52bd433b250a88988aa38e423bc1893ab3d4d2ca627e373ffda3f1dc74016113c1ee06786faed8606b6b2b7df8a3ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
