# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed66b2a1d07e051910fb140ae9a4637f8f977d7f82ca141f11dfe81c51b92bdb7d59ce9b36c2ccbf288138e6cb7a3368f00582dbab019a93e8aec4867da7cf2a

test:
  secret_key_base: ff714a22dc8b5d273575b4c785cf80c0d530424aea20bb7ee34b2e2b7e71b2da4996cdb3faecc61434783cb01113dbc3502e08dd892b0444d721f3b58eafd031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
