# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d797a2d32054bd074ff46c203f3a2673c9986aaac8b3e2c5ee213f15b08d59876fbae79538e7ca2ac9b8cc00aa06fa97b7953e447795d493f3d6694c4747aa55

test:
  secret_key_base: 011e295ac413284afca10d44eff91115ff8d6b410dbc76f883ff1c4b6de88816eb23759abc6167752671054b18f92bd8e8319137e955bd01b7bbd4468693bb61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
