# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f9884451b2f8385e747f1848f34ec409b07ddcad7c74819ccc5eb4304a8d2550679582b63cd0b12bbfbbc8cd64d9892d2b4b2287d926096250fba856be3007f

test:
  secret_key_base: e29b3a106551a10c230eb8c0a0a3e8b186747178cbb4e52af903fad9e620b041295b0387b7a08e2b7ac36b7fbd653ce2672a8af052587a42a7e962b12d337748

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
