# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daff0fb8ff451bc0d006a9ec145e5c39a0c5d3365eeb407efa4f7a6fcb282dc7a2ff9f732efe6584d96fec50a2b6b87bf540a2f5e57f562bba7411f00367eaa5

test:
  secret_key_base: 231872774eaf918fe4f0199e297483c3094e7f340ffa5072addc8e894e7b0317e3a94a025d8259d82c6f10ed07d3c545cf9a324bce89eb412b46229a53258a81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
