# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6edfe6839fc95b12b3918130d2e6d2758fa327682a25f3f22d123db82bdee954f6dc981465de3e8eddd3c7c0ac2e5da659fc03b3b657824773bb97944748d77

test:
  secret_key_base: 8bfef1f77ad263b632eb95bb2a8d364b6a91075c996a849876da3bd811dddf3fd20458b7cb3fc46c2993d0fb1bb7f610c5f09a41623c3a378c545ca1814be6e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
