# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17c6d6730e11973926e96ff6584815f596e64fec887bc3d319772a558dd6b18fdefd7216891e117ddf697f164be33214eb40fa88f2949cd3a2c381c1ec9cecd4

test:
  secret_key_base: c6fb7b660ce8ac23cecc2aaf34b4ab736476601f39f809ddafcaf74d321f13562d019df7ac5ca6c6c5749d59a360cde412a33d3315e971e76de3f0af77b1c079

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
